### ISSUE TITLE
Issue 9: Landing Page Middle Menu

### ISSUE THREAD

**Issue by sunnysiu97** [studbudd/studbudd#9]
Do all work for this task in a branch called issue-09

**Comment by kainyogi** [comment]
Middle Menu complete
Added Nunito Font
Added CSS functions
.Nunito-font
.font-large
.font-medium
.font-small
.font-bold
.font-color-white
.font-color-grey
.font-color-lightgrey
.font-color-green
.background-site
.inverted-section 
.inverted-main-header
